default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d36i5fjuibrs739c9h80-a
  port: 5432
  username: atma_nirbhar_farm_db_user
  password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P
  # url: postgresql://atma_nirbhar_farm_db_user:0F30EugdHfYajacs30xqh0kmAiB0Xj0P@dpg-d36i5fjuibrs739c9h80-a/atma_nirbhar_farm_db

development:
  <<: *default
  database: atma_nirbhar_farm_db

test:
  <<: *default
  database: mahadev_test_db

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d36i5fjuibrs739c9h80-a
    port: 5432
    database: atma_nirbhar_farm_db
    username: atma_nirbhar_farm_db_user
    password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P
  cable:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d36i5fjuibrs739c9h80-a
    port: 5432
    database: atma_nirbhar_farm_db
    username: atma_nirbhar_farm_db_user
    password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P
  queue:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d36i5fjuibrs739c9h80-a
    port: 5432
    database: atma_nirbhar_farm_db
    username: atma_nirbhar_farm_db_user
    password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P
  cache:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d36i5fjuibrs739c9h80-a
    port: 5432
    database: atma_nirbhar_farm_db
    username: atma_nirbhar_farm_db_user
    password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P
