default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: mahadev
  password: your_secure_password

development:
  <<: *default
  database: mahadev_db3

test:
  <<: *default
  database: mahadev_test_db

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d1dotrripnbc73dh6ku0-a
    port: 5432
    database: milk_delivery_app2
    username: milk_delivery_app2_user
    password: NLycabZcxnVsuRPHpEB1StBfJr4VomEV
  cable:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d1dotrripnbc73dh6ku0-a.oregon-postgres.render.com
    port: 5432
    database: milk_delivery_app2
    username: milk_delivery_app2_user
    password: NLycabZcxnVsuRPHpEB1StBfJr4VomEV
  queue:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d1dotrripnbc73dh6ku0-a.oregon-postgres.render.com
    port: 5432
    database: milk_delivery_app2
    username: milk_delivery_app2_user
    password: NLycabZcxnVsuRPHpEB1StBfJr4VomEV
  cache:
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: dpg-d1dotrripnbc73dh6ku0-a.oregon-postgres.render.com
    port: 5432
    database: milk_delivery_app2
    username: milk_delivery_app2_user
    password: NLycabZcxnVsuRPHpEB1StBfJr4VomEV