default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: dpg-d36i5fjuibrs739c9h80-a.oregon-postgres.render.com
  port: 5432
  username: atma_nirbhar_farm_db_user
  password: 0F30EugdHfYajacs30xqh0kmAiB0Xj0P

development:
  <<: *default
  database: atma_nirbhar_farm_db

test:
  <<: *default
  database: mahadev_test_db

production:
  primary:
    <<: *default
    database: atma_nirbhar_farm_db

  cable:
    <<: *default
    database: atma_nirbhar_farm_db

  queue:
    <<: *default
    database: atma_nirbhar_farm_db

  cache:
    <<: *default
    database: atma_nirbhar_farm_db
