require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.


  config.hosts = [
    "atmanirbharfarmbangalore.com", # Allow requests from main domain
    /.*\.atmanirbharfarm\.work\.gd/, # Allow requests from subdomains
    /.*\.ngrok-free\.app/,           # Allow all ngrok hosts for webhook testing
    /.*\.ngrok\.io/,                 # Allow legacy ngrok hosts
    ENV['APP_HOST'],                 # Allow requests from environment-specific host
    "atmanirbharfarmbangalore.com",
    "13.232.153.224",                # Allow requests from the production server IP
    "atmanirbharfarmbangalore.com",
    "delivery-app-ieu2.onrender.com",
    "cdc6cf4262c8.ngrok-free.app"    # Allow specific current ngrok host
  ].compact
    config.hosts << "localhost:3002"
    config.hosts << "localhost:3001"
    config.hosts << "localhost:3000"
  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Email configuration for Gmail SMTP
  config.action_mailer.raise_delivery_errors = true
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: 'smtp.gmail.com',
    port: 587,
    domain: 'gmail.com',
    user_name: 'atmanirbharfarmbangalore@gmail.com',
    password: 'yxot qrax urxf siqh',
    authentication: 'plain',
    enable_starttls_auto: true
  }

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false


  default_host = ENV.fetch('APP_HOST', 'atmanirbharfarmbangalore.com')
  config.action_mailer.default_url_options = { host: default_host }

  # Set default URL options for the main application routes
  config.action_controller.default_url_options = { host: default_host, port: nil }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  # Disabled for performance - checking migrations on every request is slow
  # config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true
  config.host_authorization = { exclude: ->(request) { request.path == "/up" } }

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
